services:
  nginx:
    restart: always
    image: store-frontend-nginx
    container_name: store-frontend-nginx
    command: /etc/nginx/startup.sh
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/startup.sh:/etc/nginx/startup.sh
      - ./nginx/localhost.crt:/etc/nginx/localhost.crt
      - ./nginx/localhost.key:/etc/nginx/localhost.key

  frontend:
    restart: always
    image: store-frontend
    working_dir: /store-fe
    volumes:
      - ./:/store-fe
    command: bash -c "pm2 start build/index.js && tail -f /dev/null"
